server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gcddb?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: syw@010903+
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.SpringBootMybatisPlus
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
